# Generated by Django 5.0.7 on 2024-09-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gist',
            field=models.TextField(default='demo', max_length=100),
            preserve_default=False,
        ),
    ]
